#!/usr/bin/env bash
# build-boringssl-ios.sh — build BoringSSL for iOS (device arm64 + simulator fat)
# from a Telegram-iOS third-party/boringssl source directory.
#
# Usage:
#   ci/build-boringssl-ios.sh --src DIR --out DIR
#
#   --src DIR   Telegram-iOS third-party/boringssl/ root (contains CMakeLists.txt
#               generated by generate_build_files.py and src/ with upstream sources).
#   --out DIR   Output root.  Artifacts:
#                 OUT/device/lib/libssl.a      (arm64 iphoneos)
#                 OUT/device/lib/libcrypto.a   (arm64 iphoneos)
#                 OUT/device/include/          (OpenSSL-compat headers from src/include/)
#                 OUT/simulator/lib/libssl.a   (fat arm64+x86_64 iphonesimulator)
#                 OUT/simulator/lib/libcrypto.a
#                 OUT/simulator/include/       (same headers)
#
# Layout mirrors what build-ios.sh expects from --openssl-root:
#   OUT/{device,simulator}/lib/lib{ssl,crypto}.a
#   OUT/{device,simulator}/include/
#
# Notes:
#   - Uses -DOPENSSL_NO_ASM=1 to avoid ASM toolchain issues on CI runners.
#   - CMAKE_SYSTEM_NAME=iOS + CMAKE_OSX_SYSROOT drives Xcode cross-compile.
#   - Simulator: arm64 and x86_64 built separately then combined with lipo.
#   - Skip rebuild if OUT/device/lib/libssl.a already exists (idempotent).

set -euo pipefail

SRC=""
OUT=""

usage() {
    printf 'Usage: %s --src DIR --out DIR\n' "$(basename "$0")" >&2
    printf '  --src DIR  Telegram-iOS third-party/boringssl/ root\n' >&2
    printf '  --out DIR  Output directory\n' >&2
    exit 2
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --src) SRC="${2:?'--src requires a path'}"; shift 2 ;;
        --out) OUT="${2:?'--out requires a path'}"; shift 2 ;;
        -h|--help) usage ;;
        *)
            printf 'error: unknown argument: %s\n' "$1" >&2
            usage
            ;;
    esac
done

[[ -n "$SRC" ]] || { printf 'error: --src is required\n' >&2; usage; }
[[ -n "$OUT" ]] || { printf 'error: --out is required\n' >&2; usage; }

[[ -f "$SRC/CMakeLists.txt" ]] || {
    printf 'error: CMakeLists.txt not found at: %s/CMakeLists.txt\n' "$SRC" >&2
    printf '       Expected Telegram-iOS third-party/boringssl/ (generated by generate_build_files.py)\n' >&2
    exit 1
}

for cmd in cmake xcrun lipo; do
    command -v "$cmd" >/dev/null 2>&1 || {
        printf 'error: required tool not found: %s\n' "$cmd" >&2; exit 1
    }
done

mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"
SRC="$(cd "$SRC" && pwd)"

HEADERS_SRC="$SRC/src/include"
[[ -d "$HEADERS_SRC/openssl" ]] || {
    printf 'error: BoringSSL headers not found at: %s/openssl/\n' "$HEADERS_SRC" >&2
    printf '       Expected src/include/openssl/ inside the BoringSSL source tree\n' >&2
    exit 1
}

# ── Skip if already built ──────────────────────────────────────────────────────
if [[ -f "$OUT/device/lib/libssl.a" && -f "$OUT/simulator/lib/libssl.a" ]]; then
    printf 'BoringSSL already built at %s — skipping\n' "$OUT"
    exit 0
fi

NCPU="$(sysctl -n hw.logicalcpu 2>/dev/null || nproc 2>/dev/null || echo 4)"

# ── Common cmake flags ─────────────────────────────────────────────────────────
COMMON_FLAGS=(
    -DOPENSSL_NO_ASM=1
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0
)

# ── Build one slice ────────────────────────────────────────────────────────────
# Args: SDK  ARCHS  BUILD_DIR  OUT_DIR
build_bssl_slice() {
    local SDK="$1"
    local ARCHS="$2"
    local BUILD_DIR="$3"
    local SLICE_OUT="$4"

    printf '\n=== Building BoringSSL for iOS SDK=%s arch=%s ===\n' "$SDK" "$ARCHS"

    cmake -S "$SRC" -B "$BUILD_DIR" \
        "${COMMON_FLAGS[@]}" \
        -DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_SYSROOT="$SDK" \
        -DCMAKE_OSX_ARCHITECTURES="$ARCHS"

    cmake --build "$BUILD_DIR" --target ssl crypto --parallel "$NCPU"

    # Telegram-iOS's flat generated CMakeLists.txt places archives at build root.
    # Locate them robustly in case a future upstream changes the layout.
    local LIBSSL="" LIBCRYPTO=""
    for candidate in "$BUILD_DIR/libssl.a" "$BUILD_DIR/ssl/libssl.a"; do
        [[ -f "$candidate" ]] && { LIBSSL="$candidate"; break; }
    done
    for candidate in "$BUILD_DIR/libcrypto.a" "$BUILD_DIR/crypto/libcrypto.a"; do
        [[ -f "$candidate" ]] && { LIBCRYPTO="$candidate"; break; }
    done
    [[ -n "$LIBSSL" && -n "$LIBCRYPTO" ]] || {
        printf 'error: libssl.a / libcrypto.a not found after build (SDK=%s arch=%s)\n' \
            "$SDK" "$ARCHS" >&2
        printf '       build dir contents:\n' >&2
        ls "$BUILD_DIR"/*.a 2>/dev/null >&2 || true
        exit 1
    }

    mkdir -p "$SLICE_OUT/lib"
    cp "$LIBSSL"   "$SLICE_OUT/lib/libssl.a"
    cp "$LIBCRYPTO" "$SLICE_OUT/lib/libcrypto.a"
}

# ── Device: arm64 iphoneos ─────────────────────────────────────────────────────
DEVICE_BUILD="$(mktemp -d "/tmp/bssl-ios-device-XXXXXX")"
trap 'rm -rf "$DEVICE_BUILD"' EXIT

build_bssl_slice iphoneos arm64 "$DEVICE_BUILD" "$OUT/device"

mkdir -p "$OUT/device/include"
cp -r "$HEADERS_SRC/." "$OUT/device/include/"

printf 'BoringSSL device done: %s\n' "$OUT/device"

# ── Simulator: arm64 + x86_64 iphonesimulator ─────────────────────────────────
SIM_ARM64_BUILD="$(mktemp -d "/tmp/bssl-ios-sim-arm64-XXXXXX")"
SIM_X86_BUILD="$(mktemp -d "/tmp/bssl-ios-sim-x86-XXXXXX")"
trap 'rm -rf "$DEVICE_BUILD" "$SIM_ARM64_BUILD" "$SIM_X86_BUILD"' EXIT

build_bssl_slice iphonesimulator arm64   "$SIM_ARM64_BUILD" "$OUT/sim-arm64-tmp"
build_bssl_slice iphonesimulator x86_64  "$SIM_X86_BUILD"   "$OUT/sim-x86-tmp"

mkdir -p "$OUT/simulator/lib"
lipo -create \
    "$OUT/sim-arm64-tmp/lib/libssl.a" \
    "$OUT/sim-x86-tmp/lib/libssl.a" \
    -output "$OUT/simulator/lib/libssl.a"
lipo -create \
    "$OUT/sim-arm64-tmp/lib/libcrypto.a" \
    "$OUT/sim-x86-tmp/lib/libcrypto.a" \
    -output "$OUT/simulator/lib/libcrypto.a"

mkdir -p "$OUT/simulator/include"
cp -r "$HEADERS_SRC/." "$OUT/simulator/include/"

rm -rf "$OUT/sim-arm64-tmp" "$OUT/sim-x86-tmp"

printf 'BoringSSL simulator done: %s\n' "$OUT/simulator"
